# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Docker image
        run: |
          docker pull nginx
          docker images
          ls

      - name: Download Artifact
        run: |
          wget https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz
          tar -xzvf tmas-cli_Linux_x86_64.tar.gz

      - name: Scan Artifact
        env:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
        run: ./tmas scan docker:nginx:latest - -VMS --saveSBOM > results.json --override overrides.yaml
        
      - name: To CSV
        run: |
          wget https://raw.githubusercontent.com/XeniaP/CS-ArtifactScanner-Report/refs/heads/main/export_report_tmas.py
          wget https://raw.githubusercontent.com/XeniaP/CS-ArtifactScanner-Report/refs/heads/main/requirements.txt
          pip install -r requirements.txt

      - name: Checking Vulnerabilities Scan Results
        run: |
          cat results.json | jq '.vulnerabilities | { totalVulnCount, criticalCount, highCount, mediumCount, lowCount, negligibleCount, unknownCount } | to_entries | .[] | "\(.key): \(.value)"'
          cat results.json | jq '.vulnerabilities.criticalCount < 1 and .vulnerability.highCount < 10 and .vulnerability.mediumCount < 30' | grep -q false && { echo "No se cumple con los criterios de vulnerabilidades. Deteniendo el pipeline."; exit 1; } || echo "Se cumple con los criterios de vulnerabilidades. Continuando con el pipeline."
        
      - name: Upload Json as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-json
          path: results.json   
